### ISSUE TITLE
Tu proyecto esta bien. ¿quieres ayuda?

### ISSUE THREAD

**Issue by SombraCancelada** [Sebastian-byte/GitG#3]
Hola tu proyecto me parece interesante, lo probé y puse datos falsos y me dice: Todo Listo! xD
te puedo ayudar en tu proyecto, solo dime que hace falta. nunca he colaborado con nada

**Comment by Sebastian-byte** [comment]
Si está bien, solo que aún no encuentro alguna forma de revisar el input
del usuario.

**Comment by SombraCancelada** [comment]
vale. voy a hacer un fork y luego tu lo revisas a ver que tal.

**Comment by Sebastian-byte** [comment]
Okey, ya revise y aplique tus cambios, si quieres colaborar más no lo preguntes y haz un fork y luego un pull request, muchas gracias!.
